# Generated by Django 2.2.5 on 2020-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=255, null=True)),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('shop_desc', models.CharField(max_length=255, null=True)),
                ('rest_date', models.CharField(max_length=255, null=True)),
                ('parking_info', models.CharField(max_length=255, null=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
